/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import utilitaire.Civilite;
import utilitaire.Libelle;

/**
 *
 * @author caoyang
 */
public class VueInscrire extends javax.swing.JFrame {

    /**
     * Creates new form VueInscrire
     */
    public VueInscrire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        btnDeconnecter = new javax.swing.JButton();
        lblStatut = new javax.swing.JLabel();
        lblInscription = new javax.swing.JLabel();
        lblRallye = new javax.swing.JLabel();
        lblVille = new javax.swing.JLabel();
        lblPays = new javax.swing.JLabel();
        lblEdition = new javax.swing.JLabel();
        lblDates = new javax.swing.JLabel();
        lblDateDeb = new javax.swing.JLabel();
        lblDateDebSaisie = new javax.swing.JLabel();
        lblDateFin = new javax.swing.JLabel();
        lblDateFinSaisie = new javax.swing.JLabel();
        lblCoureur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNumC = new javax.swing.JLabel();
        lblNumCSaisie = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblNomSaisie = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblPrenomSaisie = new javax.swing.JLabel();
        lblDateNaiss = new javax.swing.JLabel();
        lblDateNaissSaisie = new javax.swing.JLabel();
        lblGroupeSang = new javax.swing.JLabel();
        lblGroupeSangSaisie = new javax.swing.JLabel();
        lblNationalite = new javax.swing.JLabel();
        lblNationaliteSaisie = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblVehicule = new javax.swing.JLabel();
        lblNumV = new javax.swing.JLabel();
        ckbV = new javax.swing.JCheckBox();
        ckbC = new javax.swing.JCheckBox();
        btnAnnuler = new javax.swing.JButton();
        btnEnvoyer = new javax.swing.JButton();
        lblPuissance = new javax.swing.JLabel();
        lblPoids = new javax.swing.JLabel();
        txtPuissance = new javax.swing.JTextField();
        txtPoids = new javax.swing.JTextField();
        cboRallye = new javax.swing.JComboBox<>();
        cboEdition = new javax.swing.JComboBox<>();
        lblAnnee = new javax.swing.JLabel();
        lblAnneeSaisie = new javax.swing.JLabel();
        cboVille = new javax.swing.JComboBox<>();
        cboPays = new javax.swing.JComboBox<>();
        lblSexe = new javax.swing.JLabel();
        lblSexeSaisie = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(663, 489));

        btnDeconnecter.setText("btnDeconnecter");

        lblStatut.setForeground(new java.awt.Color(255, 51, 102));
        lblStatut.setText("jLabel1");

        lblInscription.setText("jLabel1");

        lblRallye.setText("jLabel1");

        lblVille.setText("jLabel2");

        lblPays.setText("jLabel3");

        lblEdition.setText("jLabel4");

        lblDates.setText("jLabel5");

        lblDateDeb.setText("jLabel6");

        lblDateDebSaisie.setText("jLabel7");

        lblDateFin.setText("jLabel8");

        lblDateFinSaisie.setText("jLabel9");

        lblCoureur.setText("jLabel10");

        lblNumC.setText("jLabel11");

        lblNumCSaisie.setText("jLabel12");

        lblNom.setText("jLabel13");

        lblNomSaisie.setText("jLabel14");

        lblPrenom.setText("jLabel15");

        lblPrenomSaisie.setText("jLabel16");

        lblDateNaiss.setText("jLabel17");

        lblDateNaissSaisie.setText("jLabel18");

        lblGroupeSang.setText("jLabel19");

        lblGroupeSangSaisie.setText("jLabel20");

        lblNationalite.setText("jLabel21");

        lblNationaliteSaisie.setText("jLabel22");

        lblVehicule.setText("jLabel23");

        lblNumV.setText("jLabel24");

        ckbV.setText("jCheckBox1");

        ckbC.setText("jCheckBox2");

        btnAnnuler.setText("jButton1");

        btnEnvoyer.setText("jButton2");

        lblPuissance.setText("jLabel25");

        lblPoids.setText("jLabel26");

        txtPuissance.setText("jTextField1");

        txtPoids.setText("jTextField4");

        cboRallye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboEdition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAnnee.setText("jLabel27");

        lblAnneeSaisie.setText("jLabel28");

        cboVille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSexe.setText("jLabel1");

        lblSexeSaisie.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatut)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnnuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnvoyer)))
                .addGap(12, 12, 12)
                .addComponent(btnDeconnecter)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblInscription))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRallye)
                                            .addComponent(lblVille)
                                            .addComponent(lblEdition))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cboVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblPays))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cboRallye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cboEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblDates))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAnnee)
                                        .addGap(28, 28, 28)
                                        .addComponent(lblAnneeSaisie)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDateDeb)
                                .addGap(18, 18, 18)
                                .addComponent(lblDateDebSaisie))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDateFin)
                                .addGap(18, 18, 18)
                                .addComponent(lblDateFinSaisie))
                            .addComponent(cboPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumV)
                                    .addComponent(lblVehicule)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckbV)
                                            .addComponent(ckbC))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPoids)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPuissance)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPuissance, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumC)
                                    .addComponent(lblCoureur)
                                    .addComponent(lblNom)
                                    .addComponent(lblDateNaiss))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumCSaisie)
                                    .addComponent(lblNomSaisie)
                                    .addComponent(lblDateNaissSaisie))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPrenom)
                                    .addComponent(lblGroupeSang))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGroupeSangSaisie)
                                    .addComponent(lblPrenomSaisie))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNationalite)
                                    .addComponent(lblSexe))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSexeSaisie)
                                    .addComponent(lblNationaliteSaisie))))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeconnecter)
                    .addComponent(btnAnnuler)
                    .addComponent(btnEnvoyer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatut)
                    .addComponent(lblInscription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRallye, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboRallye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVille)
                    .addComponent(lblPays)
                    .addComponent(cboVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdition)
                    .addComponent(cboEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDates)
                    .addComponent(lblDateDeb)
                    .addComponent(lblDateDebSaisie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateFin)
                    .addComponent(lblDateFinSaisie)
                    .addComponent(lblAnnee)
                    .addComponent(lblAnneeSaisie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCoureur)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCSaisie)
                    .addComponent(lblNumC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(lblNomSaisie)
                    .addComponent(lblPrenom)
                    .addComponent(lblPrenomSaisie)
                    .addComponent(lblSexe)
                    .addComponent(lblSexeSaisie))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateNaiss)
                    .addComponent(lblDateNaissSaisie)
                    .addComponent(lblGroupeSang)
                    .addComponent(lblGroupeSangSaisie)
                    .addComponent(lblNationalite)
                    .addComponent(lblNationaliteSaisie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVehicule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbV)
                    .addComponent(lblPuissance)
                    .addComponent(txtPuissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbC)
                    .addComponent(lblPoids)
                    .addComponent(txtPoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dessinerInscrireCompte(){
        btnDeconnecter.setText(Libelle.DECONNECTER);
        btnAnnuler.setText(Libelle.ANNULER);
        btnEnvoyer.setText(Libelle.ENVOYER);
        
        lblInscription.setText(Libelle.INSCRIPTION);
        
        lblRallye.setText(Libelle.RALLYE);
        lblEdition.setText(Libelle.EDITION);
        lblPays.setText(Libelle.PAYS);
        lblVille.setText(Libelle.VILLE);
        lblDates.setText(Libelle.DATES);
        lblDateDeb.setText(Libelle.DATEDEB);
        lblDateFin.setText(Libelle.DATEFIN);
        
        lblNom.setText(Libelle.NOM);
        lblPrenom.setText(Libelle.PRENOM);
        lblDateNaiss.setText(Libelle.DATENAISSANCE);
        lblGroupeSang.setText(Libelle.GROUPESANGUIN);
        lblNationalite.setText(Libelle.NATIONALITE);
        lblSexe.setText(Libelle.SEXE);
        
        //charger les infos de coureur
        
        cboRallye.removeAllItems();
        //charger tous les rallyes
        cboEdition.removeAllItems();
        cboPays.removeAllItems();
        cboVille.removeAllItems();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnDeconnecter;
    private javax.swing.JButton btnEnvoyer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cboEdition;
    private javax.swing.JComboBox<String> cboPays;
    private javax.swing.JComboBox<String> cboRallye;
    private javax.swing.JComboBox<String> cboVille;
    private javax.swing.JCheckBox ckbC;
    private javax.swing.JCheckBox ckbV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAnnee;
    private javax.swing.JLabel lblAnneeSaisie;
    private javax.swing.JLabel lblCoureur;
    private javax.swing.JLabel lblDateDeb;
    private javax.swing.JLabel lblDateDebSaisie;
    private javax.swing.JLabel lblDateFin;
    private javax.swing.JLabel lblDateFinSaisie;
    private javax.swing.JLabel lblDateNaiss;
    private javax.swing.JLabel lblDateNaissSaisie;
    private javax.swing.JLabel lblDates;
    private javax.swing.JLabel lblEdition;
    private javax.swing.JLabel lblGroupeSang;
    private javax.swing.JLabel lblGroupeSangSaisie;
    private javax.swing.JLabel lblInscription;
    private javax.swing.JLabel lblNationalite;
    private javax.swing.JLabel lblNationaliteSaisie;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNomSaisie;
    private javax.swing.JLabel lblNumC;
    private javax.swing.JLabel lblNumCSaisie;
    private javax.swing.JLabel lblNumV;
    private javax.swing.JLabel lblPays;
    private javax.swing.JLabel lblPoids;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblPrenomSaisie;
    private javax.swing.JLabel lblPuissance;
    private javax.swing.JLabel lblRallye;
    private javax.swing.JLabel lblSexe;
    private javax.swing.JLabel lblSexeSaisie;
    private javax.swing.JLabel lblStatut;
    private javax.swing.JLabel lblVehicule;
    private javax.swing.JLabel lblVille;
    private javax.swing.JTextField txtPoids;
    private javax.swing.JTextField txtPuissance;
    // End of variables declaration//GEN-END:variables
}
