/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.Controler;
import utilitaire.Connexion;
import utilitaire.Civilite;
import utilitaire.Libelle;

/**
 *
 * @author caoyang
 */
public class VueInscrireCompte extends javax.swing.JFrame {
    
    Connexion conn;
    Controler controler;
    
    /**
     * Creates new form VueSInscrire
     */
    public VueInscrireCompte() {
        this.conn = new Connexion();
        this.controler = new Controler();
        
        initComponents();
        dessinerInscrireCompte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSinscrire = new javax.swing.JLabel();
        btnConnecter = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblMdp = new javax.swing.JLabel();
        txtMdp = new javax.swing.JPasswordField();
        lblDateNaiss = new javax.swing.JLabel();
        txtDateNaiss = new javax.swing.JTextField();
        lblGroupeSang = new javax.swing.JLabel();
        lblNationalite = new javax.swing.JLabel();
        txtGroupeSang = new javax.swing.JTextField();
        txtNationalite = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblErreur = new javax.swing.JLabel();
        lblSexe = new javax.swing.JLabel();
        cboSexe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(663, 489));

        lblSinscrire.setText("jLabel1");

        btnConnecter.setText("jButton1");
        btnConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnecterActionPerformed(evt);
            }
        });

        lblEmail.setText("jLabel2");

        txtEmail.setText("jTextField1");

        lblMdp.setText("jLabel1");

        txtMdp.setText("jPasswordField1");

        lblDateNaiss.setText("jLabel3");

        txtDateNaiss.setText("jTextField2");

        lblGroupeSang.setText("jLabel4");

        lblNationalite.setText("jLabel5");

        txtGroupeSang.setText("jTextField3");

        txtNationalite.setText("jTextField4");

        btnSave.setText("jButton1");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblNom.setText("jLabel1");

        txtNom.setText("jTextField1");

        lblPrenom.setText("jLabel2");

        txtPrenom.setText("jTextField2");

        lblErreur.setForeground(new java.awt.Color(255, 0, 0));
        lblErreur.setText("jLabel1");

        lblSexe.setText("jLabel1");

        cboSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnConnecter)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNationalite)
                                    .addGap(176, 176, 176)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblSexe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErreur)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblMdp)
                            .addComponent(lblDateNaiss)
                            .addComponent(lblGroupeSang)
                            .addComponent(lblNom))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGroupeSang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                        .addComponent(lblPrenom))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblSinscrire)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConnecter)
                .addGap(14, 14, 14)
                .addComponent(lblSinscrire)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMdp)
                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateNaiss)
                    .addComponent(txtDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexe)
                    .addComponent(cboSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNationalite)
                    .addComponent(txtNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGroupeSang)
                    .addComponent(txtGroupeSang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(lblErreur))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnecterActionPerformed
        this.dispose();
        this.controler.Deconnecter();
    }//GEN-LAST:event_btnConnecterActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String em = txtEmail.getText();
        String mdp = txtMdp.getText();
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        String dateN = txtDateNaiss.getText();
        String groupeS = txtGroupeSang.getText();
        String nationalite = txtNationalite.getText();
        String sexe = cboSexe.getSelectedItem().toString();
        
        switch(sexe){
            case Civilite.MONSIEUR : 
                sexe = Civilite.HOMME;break;
            case Civilite.MADAME : 
                sexe = Civilite.FEMME;break;
        }
        
        if(this.conn.checkConnExist(txtEmail.getText())){
            lblErreur.setText("Cet adresse d'email existe déjà");
        }else{
            if(em.equals("")||mdp.equals("")||nom.equals("")||prenom.equals("")||dateN.equals("")||groupeS.equals("")){
                lblErreur.setText("Veillez compléter vos données");
            } else {
                this.dispose();
                this.controler.SaveInscrireCompte(em, mdp, nom, prenom, sexe, dateN, groupeS,nationalite);                
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void dessinerInscrireCompte(){
        btnConnecter.setText(Libelle.DECONNECTER);
        btnSave.setText(Libelle.SAVE);
        
        lblSinscrire.setText(Libelle.SINSCRIRE);
        
        lblEmail.setText(Libelle.EMAIL);
        lblMdp.setText(Libelle.MDP);
        txtEmail.setText(Libelle.VIDE);
        txtMdp.setText(Libelle.VIDE);
        lblErreur.setText(Libelle.VIDE);
        
        lblNom.setText(Libelle.NOM);
        lblPrenom.setText(Libelle.PRENOM);
        lblDateNaiss.setText(Libelle.DATENAISSANCE);
        lblGroupeSang.setText(Libelle.GROUPESANGUIN);
        lblNationalite.setText(Libelle.NATIONALITE);
        lblSexe.setText(Libelle.SEXE);
        
        txtNom.setText(Libelle.VIDE);
        txtPrenom.setText(Libelle.VIDE);
        txtDateNaiss.setText(Libelle.VIDE);
        txtGroupeSang.setText(Libelle.VIDE);
        txtNationalite.setText(Libelle.VIDE);
        
        cboSexe.removeAllItems();
        cboSexe.addItem(Civilite.MONSIEUR);
        cboSexe.addItem(Civilite.MADAME);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnecter;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboSexe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDateNaiss;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErreur;
    private javax.swing.JLabel lblGroupeSang;
    private javax.swing.JLabel lblMdp;
    private javax.swing.JLabel lblNationalite;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblSexe;
    private javax.swing.JLabel lblSinscrire;
    private javax.swing.JTextField txtDateNaiss;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGroupeSang;
    private javax.swing.JPasswordField txtMdp;
    private javax.swing.JTextField txtNationalite;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables

}
